[add] Rubyアウトプット課題（グループ分け問題）を追加
niha-2/hc_practice pull request #3
Opened 2023-06-27 11:30 UTC by niha-2

## 課題のリンク

* [Rubyアウトプット課題（グループ分け問題）](https://github.com/happiness-chain/practice/blob/main/08_ruby/001_%E3%82%B0%E3%83%AB%E3%83%BC%E3%83%97%E5%88%86%E3%81%91%E5%95%8F%E9%A1%8C.md)

## やったこと

* Rubyアウトプット課題（グループ分け問題）を追加

## 動作確認方法

* ターミナルで、random.rbが存在するフォルダに移動し、`` ruby random.rb``コマンドを実行する

## その他

* 実行結果
<img width="294" alt="image" src="https://github.com/niha-2/hc_practice/assets/109413871/b1a8e2d0-6402-4284-a706-a4ab2076b0cf">

2023-06-28 21:55 UTC, ihatov08 requested changes
> また表示結果はアルファベット順にしてください。

対応お願いします！

2023-06-29 09:42 UTC, niha-2 commented
> > また表示結果はアルファベット順にしてください。
> 
> 対応お願いします！

読み飛ばしていました、すみません。
修正しましたのでご確認お願いします。

2023-06-29 22:04 UTC, ihatov08 approved these changes
確認しました、LGTMです！
ちなみに私なら以下のようにします。

https://gist.github.com/ihatov08/c4a1290bd18759eea153baf9cb692fb0

2023-06-30 10:50 UTC, niha-2 commented
> 確認しました、LGTMです！ ちなみに私なら以下のようにします。
> 
> https://gist.github.com/ihatov08/c4a1290bd18759eea153baf9cb692fb0

なるほど、すごくすっきりしていてわかりやすいですね。
配列同士で引き算のように書けるんですね。
参考にさせていただきます！

2023-06-30 10:51 UTC, merged